#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "在 GitHub 上查看":
    - "//github.com/mrzhqiang/idea-helper"
